# Generated by Django 4.0 on 2022-03-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('Name', models.CharField(max_length=120)),
                ('Mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Type', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=5000)),
                ('Image', models.ImageField(upload_to='Family_images')),
                ('Food', models.CharField(max_length=500)),
                ('Decoration', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Type', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=5000)),
                ('Image', models.ImageField(upload_to='Culture_images')),
                ('Food', models.CharField(max_length=50)),
                ('Decoration', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Type', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=5000)),
                ('Image', models.ImageField(upload_to='Charity_images')),
                ('Food', models.CharField(max_length=50)),
                ('Decoration', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=50)),
                ('Desc', models.TextField(max_length=5000)),
                ('Image_name', models.ImageField(upload_to='Buisness_images')),
                ('Food', models.CharField(max_length=50)),
                ('Pubilcity', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookevent',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('People', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Event', models.CharField(max_length=150)),
                ('Food', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=1200)),
                ('Message', models.CharField(max_length=1200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
